/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Sulaiman Ahmed
 */
public class HomeFrame extends javax.swing.JFrame {
    static Game game ;
    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        setLocationRelativeTo(null) ;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        MSLabel = new javax.swing.JLabel();
        EasyButton = new javax.swing.JRadioButton();
        MediumButton = new javax.swing.JRadioButton();
        HardButton = new javax.swing.JRadioButton();
        ExitButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MINESWEEPER");
        setBackground(new java.awt.Color(51, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(0, 255, 255));

        MSLabel.setBackground(new java.awt.Color(0, 0, 0));
        MSLabel.setFont(new java.awt.Font("Txt", 1, 36)); // NOI18N
        MSLabel.setForeground(new java.awt.Color(255, 0, 51));
        MSLabel.setText("MINESWEEPER");

        EasyButton.setSelected(true);
        EasyButton.setText("Easy");
        EasyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EasyButtonMouseClicked(evt);
            }
        });

        MediumButton.setText("Medium");
        MediumButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MediumButtonMouseClicked(evt);
            }
        });

        HardButton.setText("Hard");
        HardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HardButtonMouseClicked(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(255, 0, 0));
        ExitButton.setFont(new java.awt.Font("Vineta BT", 1, 11)); // NOI18N
        ExitButton.setText("EXIT");
        ExitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitButtonMouseClicked(evt);
            }
        });

        PlayButton.setBackground(new java.awt.Color(51, 255, 51));
        PlayButton.setFont(new java.awt.Font("Vineta BT", 1, 11)); // NOI18N
        PlayButton.setText("PLAY");
        PlayButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlayButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EasyButton)
                        .addGap(72, 72, 72)
                        .addComponent(MediumButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HardButton))
                    .addComponent(MSLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PlayButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MSLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EasyButton)
                    .addComponent(MediumButton)
                    .addComponent(HardButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PlayButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlayButtonMouseClicked
        // TODO add your handling code here:
        String option ;
        if(EasyButton.isSelected()) option = "1" ;
        else if(MediumButton.isSelected()) option = "2" ;
        else if(HardButton.isSelected()) option = "3" ;
        else option = "1" ;
        game = new Game(option) ;
        dispose();
    }//GEN-LAST:event_PlayButtonMouseClicked

    private void ExitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0) ;
    }//GEN-LAST:event_ExitButtonMouseClicked

    private void EasyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EasyButtonMouseClicked
        // TODO add your handling code here:
        if(HardButton.isSelected()) HardButton.doClick();
        if(MediumButton.isSelected()) MediumButton.doClick();
    }//GEN-LAST:event_EasyButtonMouseClicked

    private void MediumButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MediumButtonMouseClicked
        // TODO add your handling code here:
        if(HardButton.isSelected()) HardButton.doClick();
        if(EasyButton.isSelected()) EasyButton.doClick();
    }//GEN-LAST:event_MediumButtonMouseClicked

    private void HardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HardButtonMouseClicked
        // TODO add your handling code here:
        if(EasyButton.isSelected()) EasyButton.doClick();
        if(MediumButton.isSelected()) MediumButton.doClick();
    }//GEN-LAST:event_HardButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton EasyButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JRadioButton HardButton;
    private javax.swing.JLabel MSLabel;
    private javax.swing.JRadioButton MediumButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
